In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
from sklearn.datasets import load_iris
data =load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

### make Data Frame

In [8]:
df =pd.DataFrame(data =data.data ,columns=data.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
df["target"] =data.target

In [10]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [11]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
145       2  
146       2  
147       2  
148       2  
149       2

In [12]:
df.duplicated().sum()

1

In [13]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [14]:
df.target.unique()

array([0, 1, 2])

In [15]:
df =df[df.target != 2]

In [16]:
df.target.unique()

array([0, 1])

### Split data into X ,y

In [17]:
X =df.iloc[:,:-1]
y =df.iloc[:,-1]

In [18]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [19]:
y

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int64

In [20]:
df.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                 int64
dtype: object

### train test split

In [21]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,y_train ,y_test =train_test_split(X,y,test_size=0.20 ,random_state=12)

In [22]:
X_train.shape ,X_test.shape ,y_train.shape ,y_test.shape

((80, 4), (20, 4), (80,), (20,))

In [23]:
from sklearn.linear_model import LogisticRegression
classifier =LogisticRegression()

In [24]:
classifier

LogisticRegression()

In [25]:
classifier.fit(X_train ,y_train)

LogisticRegression()

In [26]:
y_pred =classifier.predict(X_test)

In [27]:
y_pred

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0])

In [28]:
classifier.predict_proba(X_test)

array([[0.9767676 , 0.0232324 ],
       [0.96044995, 0.03955005],
       [0.02029959, 0.97970041],
       [0.98782646, 0.01217354],
       [0.00312057, 0.99687943],
       [0.96127843, 0.03872157],
       [0.01936721, 0.98063279],
       [0.98090025, 0.01909975],
       [0.97335926, 0.02664074],
       [0.05939721, 0.94060279],
       [0.97400899, 0.02599101],
       [0.9738872 , 0.0261128 ],
       [0.97139236, 0.02860764],
       [0.96912074, 0.03087926],
       [0.97256793, 0.02743207],
       [0.00328305, 0.99671695],
       [0.00460521, 0.99539479],
       [0.94132163, 0.05867837],
       [0.00350048, 0.99649952],
       [0.9833698 , 0.0166302 ]])

In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score ,classification_report
print(confusion_matrix(y_test ,y_pred))

[[13  0]
 [ 0  7]]


In [30]:
accuracy_score(y_test ,y_pred)

1.0

In [31]:
print(classification_report(y_test ,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00         7

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [32]:
from sklearn.metrics import roc_curve ,auc
import matplotlib.pyplot as plt
y_pred_proba =classifier.predict_proba(X_test)[:,1]

In [33]:
y_pred_proba

array([0.0232324 , 0.03955005, 0.97970041, 0.01217354, 0.99687943,
       0.03872157, 0.98063279, 0.01909975, 0.02664074, 0.94060279,
       0.02599101, 0.0261128 , 0.02860764, 0.03087926, 0.02743207,
       0.99671695, 0.99539479, 0.05867837, 0.99649952, 0.0166302 ])

In [34]:
fpr ,tpr ,treshold =roc_curve(y_test ,y_pred_proba)

In [35]:
fpr

array([0., 0., 0., 1.])

In [36]:
tpr

array([0.        , 0.14285714, 1.        , 1.        ])

In [37]:
treshold

array([1.99687943, 0.99687943, 0.94060279, 0.01217354])

In [38]:
roc_auc =auc(fpr ,tpr)
roc_auc

1.0

In [39]:
from sklearn.linear_model import LogisticRegressionCV## Home Work 
from sklearn.model_selection import KFold 

In [40]:
cv =KFold(n_splits=5)

In [41]:
from sklearn.model_selection import cross_val_score
score =cross_val_score(classifier ,X_train ,y_train,cv=cv,scoring="accuracy")

In [42]:
score

array([1., 1., 1., 1., 1.])

In [43]:
np.mean(score)

1.0

In [47]:
from sklearn.model_selection import GridSearchCV
param ={"penalty":("l1","l2","elasticnet"),"C":[1,2,3,4,20,30,50],"solver":['lbfgs','liblinear','newton-cg','newton-cholesky','sag','saga']}
g_clf =GridSearchCV(classifier ,param_grid=param)
g_clf.fit(X_train ,y_train)

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 20, 30, 50],
                         'penalty': ('l1', 'l2', 'elasticnet'),
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']})

In [48]:
g_clf.best_score_

1.0

In [49]:
g_clf.best_params_

{'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}

In [52]:
from sklearn.linear_model import LogisticRegression
classifiers =LogisticRegression(penalty="l1",C=1.0,solver="liblinear")
classifiers.fit(X_train ,y_train)

LogisticRegression(penalty='l1', solver='liblinear')

In [53]:
clas_y_pred =classifiers.predict(X_test)
clas_y_pred

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0])

In [54]:
from sklearn.metrics import classification_report ,accuracy_score ,confusion_matrix
print(confusion_matrix(y_test ,clas_y_pred))
print(accuracy_score(y_test ,clas_y_pred))
print(classification_report(y_test ,clas_y_pred))

[[13  0]
 [ 0  7]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00         7

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



### Pickle the model

In [44]:
import pickle 
pickle.dump(classifier ,open("Classifier.pkl","wb"))

In [45]:
model =pickle.load(open("Classifier.pkl","rb"))

In [46]:
model.predict(X_test)

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0])