In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_iris
data =load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
df =pd.DataFrame(data.data ,columns=data.feature_names)

In [4]:
df["target"] =data.target

In [5]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [10]:
df.target.value_counts()

0    50
1    50
2    50
Name: target, dtype: int64

In [11]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

#### Seprate  the X and Y columns

In [12]:
X =df.iloc[:,:-1]
y =df.iloc[:,-1]

In [13]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [14]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

#### Train the model

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.25,random_state=12)

In [18]:
X_train.shape ,X_test.shape

((112, 4), (38, 4))

#### Build the multinomial model

In [19]:
from sklearn.linear_model import LogisticRegression
model =LogisticRegression()
model.fit(X_train ,y_train)
y_pred =model.predict(X_test)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [21]:
y_pred

array([0, 2, 0, 1, 2, 2, 2, 0, 2, 0, 1, 0, 0, 0, 1, 2, 2, 1, 0, 1, 0, 1,
       2, 1, 0, 2, 2, 1, 0, 0, 0, 1, 2, 0, 2, 0, 1, 1])

In [22]:
from sklearn.metrics import confusion_matrix ,accuracy_score,classification_report
print(confusion_matrix(y_test ,y_pred))

[[15  0  0]
 [ 0 11  1]
 [ 0  0 11]]


In [23]:
print(accuracy_score(y_test ,y_pred))

0.9736842105263158


In [24]:
print(classification_report(y_test ,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.92      0.96        12
           2       0.92      1.00      0.96        11

    accuracy                           0.97        38
   macro avg       0.97      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38



#### Check the best parameter using grid search CV 

In [31]:
import warnings
warnings.filterwarnings("ignore")

In [37]:
from sklearn.model_selection import GridSearchCV
# classifier =LogisticRegression()
param ={"penalty":("l1","l2","elasticnet"),"C":[1,2,3,4,20,30,50],"solver":['lbfgs','liblinear','newton-cg','newton-cholesky','sag','saga']}
clf =GridSearchCV(model ,param_grid=param,verbose=3)
clf.fit(X_train ,y_train)

Fitting 5 folds for each of 126 candidates, totalling 630 fits
[CV 1/5] END .......C=1, penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 2/5] END .......C=1, penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 3/5] END .......C=1, penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 4/5] END .......C=1, penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 5/5] END .......C=1, penalty=l1, solver=lbfgs;, score=nan total time=   0.0s
[CV 1/5] END .C=1, penalty=l1, solver=liblinear;, score=1.000 total time=   0.0s
[CV 2/5] END .C=1, penalty=l1, solver=liblinear;, score=0.957 total time=   0.0s
[CV 3/5] END .C=1, penalty=l1, solver=liblinear;, score=0.864 total time=   0.0s
[CV 4/5] END .C=1, penalty=l1, solver=liblinear;, score=1.000 total time=   0.0s
[CV 5/5] END .C=1, penalty=l1, solver=liblinear;, score=0.955 total time=   0.0s
[CV 1/5] END ...C=1, penalty=l1, solver=newton-cg;, score=nan total time=   0.0s
[CV 2/5] END ...C=1, penalty=l1, solver=newton

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 20, 30, 50],
                         'penalty': ('l1', 'l2', 'elasticnet'),
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             verbose=3)

In [36]:
clf.best_params_

{'C': 1, 'penalty': 'l2', 'solver': 'sag'}

In [38]:
from sklearn.model_selection import RandomizedSearchCV
r_clf =RandomizedSearchCV(model, param_distributions=param ,verbose=3)
r_clf.fit(X_train ,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END C=50, penalty=l2, solver=liblinear;, score=1.000 total time=   0.0s
[CV 2/5] END C=50, penalty=l2, solver=liblinear;, score=0.957 total time=   0.0s
[CV 3/5] END C=50, penalty=l2, solver=liblinear;, score=0.864 total time=   0.0s
[CV 4/5] END C=50, penalty=l2, solver=liblinear;, score=1.000 total time=   0.0s
[CV 5/5] END C=50, penalty=l2, solver=liblinear;, score=0.909 total time=   0.0s
[CV 1/5] END .....C=30, penalty=l2, solver=saga;, score=1.000 total time=   0.0s
[CV 2/5] END .....C=30, penalty=l2, solver=saga;, score=0.957 total time=   0.0s
[CV 3/5] END .....C=30, penalty=l2, solver=saga;, score=0.909 total time=   0.0s
[CV 4/5] END .....C=30, penalty=l2, solver=saga;, score=1.000 total time=   0.0s
[CV 5/5] END .....C=30, penalty=l2, solver=saga;, score=1.000 total time=   0.0s
[CV 1/5] END .C=4, penalty=l2, solver=liblinear;, score=1.000 total time=   0.0s
[CV 2/5] END .C=4, penalty=l2, solver=liblinear;

RandomizedSearchCV(estimator=LogisticRegression(),
                   param_distributions={'C': [1, 2, 3, 4, 20, 30, 50],
                                        'penalty': ('l1', 'l2', 'elasticnet'),
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   verbose=3)

In [39]:
r_clf.best_estimator_

LogisticRegression(C=4)

In [40]:
r_clf.best_params_

{'solver': 'lbfgs', 'penalty': 'l2', 'C': 4}

In [41]:
r_clf.best_score_

0.9735177865612649